[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "18.17.0"
  PYTHON_VERSION = "3.8"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = true
  conditions = {Path = "/_next/static/*"} 